### ISSUE TITLE
Update demo 

### ISSUE THREAD

**Issue by danmindru** [ng-milk/angular-sticky-navigation-directive#2]
It could be helpful to extend the demo and show the sidebar example from [#1] too.
I guess the right thing to do here would be to make a 'master' page that links to demo nr. 1, nr. 2 and so on.

**Comment by llattes** [comment]
I just sent you a new example file linked from the existing `index.html`. Be careful before merging because I'm not sure if http://ng-milk.github.io/angular-sticky-navigation-directive/ will work properly OOTB. Check #3 for details.

**Comment by danmindru** [comment]
Awesome that you made the demo.
`gh-pages` works ok, thanks for the heads up :-)
